version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tech
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
